extension: ["ts"]
node-option: ["experimental-specifier-resolution=node", "loader=ts-node/esm", "no-warnings"]
spec: ["test/**/*.test.ts"]
ui: 'bdd'
require: test/helper.ts
watch-ignore:
  - 'node_modules'
