env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
  - eslint-plugin-tsdoc
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  object-curly-spacing:
    - error
    - always
  tsdoc/syntax: warn
  prefer-template: error
  no-console: warn

overrides:
  - files: ["lib/tasks/Jakefile.ts", "lib/MigrationExecutor.ts"]
    rules:
      no-console: off
